### ISSUE TITLE
System memory usage reaches capacity during upload to new receiver

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/results-collection#573]
Following successful invocation of `wpt run`, each build "worker" uploads a WPT report file to the build master. To facilitate this, the build master ensures a dedicated directory is available on its data storage partition. Over the past few days, the directory creation step has been failing sporadically.

The error is a Python `OSError` ("Cannot allocate memory") originating from the invocation of `mkdir` on the Build master.

<details>
  <summary>Complete error stack</summary>

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 577, in startStep
        self.results = yield self.run()
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
        result = g.send(result)
      File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 704, in run
        results = yield self.start()
      File "/usr/local/lib/python2.7/dist-packages/buildbot/steps/master.py", line 151, in start
        path=self.masterWorkdir, usePTY=self.usePTY, env=env)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 340, in spawnProcess
        processProtocol, uid, gid, childFDs)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 745, in __init__
        self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 420, in _fork
        self.pid = os.fork()
    exceptions.OSError: [Errno 12] Cannot allocate memory

</details>

Uploading to the new receiver involves loading the entire WPT report into memory, and this exhausts system resources. This appears to account for the sporadic nature of the failures, since it would only effect those builds which completed while uploading was in progress.

The upload process has to handle the complete WPT report in two stages:

1. Consolidating partial WPT reports uploaded by the workers (which are each assigned a "chunk" of WPT)
2. Uploading the data to the results receiver

To limit memory consumption during the first stage, the upload script should be modified to incrementally append the partial data to a text file (which will only describe a valid JSON document after each "chunk" result file has been open, read, and closed in turn).

To limit memory consumption during the second stage, I believe we will need to move away from [the venerable Requests library](http://docs.python-requests.org/en/latest/). I'm reluctant to leave behind such a widely-used and recommended module, but [it seems to require that multipart form data is fully loaded in memory](https://github.com/requests/requests/blob/d1aeb7ea8cec833e61ea390a6c19ef8b7ac3e4e7/requests/models.py#L156-L163) (see also [the underlying implementation in the `urllib3` module](https://urllib3.readthedocs.io/en/latest/reference/index.html#urllib3.filepost.encode_multipart_formdata)).

This is a high-priority issue because it directly interferes with the availability of test results. I intend to start work on a fix tomorrow.

**Comment by jugglinmike** [comment]
I decided that the first stage is a much larger concern. Since addressing that requires less change (and in particular, less new code), I'd like to proceed initially by limiting the fix to that. I will re-open this issue if experience shows that the second stage is still relevant.

Prior to making this decision, I extended the coverage of the test suite to include more aspects of the upload process. Although we may not need to implement the second optimization described above, those tests are still valuable for the avoidance of regressions. I've merged them via 083bd3102054f8e4e932fad748a15f4c8dd8b72e
